CREATE DATABASE [TRADEProd_DW]
GO

USE [TRADEProd_DW]
GO

/******	Creacion tabla FACT	******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACT_VENTAS](
	[KEY_VENDEDOR] [int] NOT NULL,
	[KEY_CLIENTE] [int] NOT NULL ,
	[KEY_TIEMPO] [int] NOT NULL ,
	[KEY_PRODUCTO] [int] NOT NULL ,
	[KEY_SUCURSAL] [int] NOT NULL ,
	
	[DOCUMENTO] [nvarchar](255) NOT NULL,
	[CODIGO_PRODUCTO] [nvarchar](255) NOT NULL,
	[TOTAL_NETO] [int] NULL,
	[IMPUESTO] [int] NULL,
	[PRECIO_UNITARIO] [int] NULL,
	[CANTIDAD] [int] NULL,
	[TOTAL_PESOS] [int] NULL,
	[TOTAL_DOLAR] [int] NULL,
	CONSTRAINT PK_FACT_VENTAS PRIMARY KEY ([DOCUMENTO], [CODIGO_PRODUCTO])
);


/******	Creacion DIM_PRODUCTOS	******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_PRODUCTOS](
	[KEY_PRODUCTO] INT IDENTITY NOT NULL PRIMARY KEY,
	[CODIGO_PRODUCTO] [nvarchar](255) NOT NULL,
	[NOMBRE] [nvarchar](255) NULL,
	[CATEGORIA] [nvarchar](255) NULL,
	[PRECIO_UNITARIO] [int] NULL,
	[COSTO_UNITARIO] [int] NULL)
GO




/******	Creacion DIM_CLIENTES	******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_CLIENTES](
	[KEY_CLIENTE] INT IDENTITY NOT NULL PRIMARY KEY,
	[ID_CLIENTE] [nvarchar](255) NOT NULL,
	[NOMBRE] [nvarchar](255) NULL,
	[APELLIDO] [nvarchar](255) NULL,
	[EDAD] [smallint] NULL,
	[ESTADO_CIVIL] [nvarchar](255) NULL,
	[RESIDENCIA] [nvarchar](255) NULL,
	[ORIGEN] [nvarchar](255) NULL)
GO



/******Creacion DIM_SUCURSALES ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_SUCURSALES](
	[KEY_SUCURSAL] INT IDENTITY NOT NULL PRIMARY KEY,
	[NOMBRE_SUCURSAL] [nvarchar](255) NULL,
	[COMUNA] [nvarchar](255) NULL,
	[PROVINCIA] [nvarchar](255) NULL,
	[REGION] [nvarchar](255) NULL)
GO





/******Creacion DIM_VENDEDORES ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_VENDEDORES](
	[KEY_VENDEDOR] INT IDENTITY NOT NULL PRIMARY KEY,
	[Nombre] [nvarchar](255) NULL,
	[Apellido] [nvarchar](255) NULL,
	[TIPO_ CAPACITACION] [nvarchar](255) NULL,
	[HORAS_CAPACITACION] [smallint] NULL)
GO


/******Creacion DIM_TIEMPO ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_TIEMPO] (
   [KEY_TIEMPO] INT NOT NULL PRIMARY KEY,
   [FECHA] DATE,
   [DIA] INT,
   [MES] INT,
   [ANIO] INT,
)
GO




/******Creacion [FK_VENTAS_PRODUCTOS] ******/
ALTER TABLE [dbo].[FACT_VENTAS]  WITH CHECK ADD  CONSTRAINT [FK_VENTAS_PRODUCTOS] FOREIGN KEY([KEY_PRODUCTO])
REFERENCES [dbo].[DIM_PRODUCTOS] ([KEY_PRODUCTO])
GO

ALTER TABLE [dbo].[FACT_VENTAS] CHECK CONSTRAINT [FK_VENTAS_PRODUCTOS]
GO



/******Creacion [FK_VENTAS_CLIENTES] ******/
ALTER TABLE [dbo].[FACT_VENTAS]  WITH CHECK ADD  CONSTRAINT [FK_VENTAS_CLIENTES] FOREIGN KEY([KEY_CLIENTE])
REFERENCES [dbo].[DIM_CLIENTES] ([KEY_CLIENTE])
GO

ALTER TABLE [dbo].[FACT_VENTAS] CHECK CONSTRAINT [FK_VENTAS_CLIENTES]
GO



/******Creacion [FK_VENTAS_SUCURSALES] ******/
ALTER TABLE [dbo].[FACT_VENTAS]  WITH CHECK ADD  CONSTRAINT [FK_VENTAS_SUCURSALES] FOREIGN KEY([KEY_SUCURSAL])
REFERENCES [dbo].[DIM_SUCURSALES] ([KEY_SUCURSAL])
GO

ALTER TABLE [dbo].[FACT_VENTAS] CHECK CONSTRAINT [FK_VENTAS_SUCURSALES]
GO




/******Creacion [FK_VENTAS_VENDEDORES] ******/
ALTER TABLE [dbo].[FACT_VENTAS]  WITH CHECK ADD  CONSTRAINT [FK_VENTAS_VENDEDORES] FOREIGN KEY([KEY_VENDEDOR])
REFERENCES [dbo].[DIM_VENDEDORES] ([KEY_VENDEDOR])
GO

ALTER TABLE [dbo].[FACT_VENTAS] CHECK CONSTRAINT [FK_VENTAS_VENDEDORES]
GO



/******Creacion [FK_VENTAS_TIEMPO] ******/
ALTER TABLE [dbo].[FACT_VENTAS]  WITH CHECK ADD  CONSTRAINT [FK_VENTAS_TIEMPO] FOREIGN KEY([KEY_TIEMPO])
REFERENCES [dbo].[DIM_TIEMPO] ([KEY_TIEMPO])
GO

ALTER TABLE [dbo].[FACT_VENTAS] CHECK CONSTRAINT [FK_VENTAS_TIEMPO]
GO